export default {
  env: `prod`,
  dev: ``,
  devApi: ``,
  stg: ``,
  stgApi: ``,
  qa: ``,
  qaApi: ``,
  prod: `https://demo.nopcommerce.com/`,
  prodApi: ``,
  ownerAuth: `tests/data/storageState/ownerAuth.json`,
  adminAuth: `tests/data/storageState/adminAuth.json`,
  downloadFiles: `reports/download/`,
  lighthouse: `reports/lighthouse-report/LighthouseReport.html`,
  testUrl: `https://www.notion.so/`,
  issueUrl: `https://trello.com/`,
  logsFile: `reports/logs/info.log`,
  reportFolder: `reports`,
  allureResults: `allure-results`,
  monocartReport: `reports/monocart-report/report.html`,
  playWrightReport: `reports/playwright-report`,
  customReporter: `./src/lib/CustomReporter.ts`,
  testResultJson: `reports/json-report/test-results.json`,
  testArtifacts: `reports/test-artifacts`,
};
