name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install xvfb
      run: sudo apt-get install -y xvfb

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: xvfb-run npx playwright test  # Run the tests with xvfb

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: reports/playwright-report/
        retention-days: 30
       
    - name: Setup Pages
      uses: actions/configure-pages@v2
     
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
       # Upload entire repository
       path: reports/playwright-report/
      
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
    
    # - name: Deploy Playwright Report to GitHub Pages
    #   if: ${{ always() }}
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: reports/playwright-report/index.html

    # - name: Notify Slack
    #   if: always()  # Notify regardless of success or failure
    #   uses: rtCamp/action-slack-notify@v2
    #   env:
    #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
    #   with:
    #     status: ${{ job.status }}
    #     job_name: Playwright Tests